language: php
php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - SIMPLETEST_DB=mysql://root:@localhost/elife_2_0
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

services:
  - mysql

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - mysql --execute='CREATE DATABASE elife_2_0;'
  - composer --verbose install
  - composer drupal-scaffold

script:
  - cp $TRAVIS_BUILD_DIR/config/travis.settings.php $TRAVIS_BUILD_DIR/config/local.settings.php
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush site-install config_installer --account-name=admin --account-pass=admin --site-name="eLife 2.0" --yes
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c core --exclude-group Composer
  - $TRAVIS_BUILD_DIR/vendor/bin/drush
  - $TRAVIS_BUILD_DIR/vendor/bin/drupal
