resources:
  labs_experiment_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
